AsistenteCorreos
ncarvajalc/codelabs-iau pull request #5
Opened 2024-09-03 22:23 UTC by PauMurillo28

CodeLab Kennet IAu

2024-09-03 22:26 UTC, ncarvajalc commented
@PauMurillo28 no sé si necesites que te verifique el PR o si alguien más lo va a hacer. Me avisas si necesitas que le dé permisos a alguien para poder integrar tus cambios.

2024-09-04 01:04 UTC, PauMurillo28 commented
Holaaa, si porfa

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Nicolás Carvajal ***@***.***>
Enviado: Tuesday, September 3, 2024 5:26:30 PM
Para: ncarvajalc/codelabs-iau ***@***.***>
Cc: Maria Paula Murillo Corredor ***@***.***>; Mention ***@***.***>
Asunto: Re: [ncarvajalc/codelabs-iau] AsistenteCorreos (PR #5)


@PauMurillo28<https://github.com/PauMurillo28> no sé si necesites que te verifique el PR o si alguien más lo va a hacer. Me avisas si necesitas que le dé permisos a alguien para poder integrar tus cambios.

—
Reply to this email directly, view it on GitHub<https://github.com/ncarvajalc/codelabs-iau/pull/5#issuecomment-2327548521>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5P2FULMJOBJA4HZASK3EJTZUYZRNAVCNFSM6AAAAABNTBU2OGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRXGU2DQNJSGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-04 01:05 UTC, ncarvajalc commented
@PauMurillo28 Sí porfa a qué? Te la reviso o quieres que le dé permisos a alguien?

2024-09-04 01:25 UTC, PauMurillo28 commented
Me lo puedes revisar por favor?

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Nicolás Carvajal ***@***.***>
Enviado: Tuesday, September 3, 2024 8:06:19 PM
Para: ncarvajalc/codelabs-iau ***@***.***>
Cc: Maria Paula Murillo Corredor ***@***.***>; Mention ***@***.***>
Asunto: Re: [ncarvajalc/codelabs-iau] AsistenteCorreos (PR #5)


@PauMurillo28<https://github.com/PauMurillo28> Sí porfa a qué? Te la reviso o quieres que le dé permisos a alguien?

—
Reply to this email directly, view it on GitHub<https://github.com/ncarvajalc/codelabs-iau/pull/5#issuecomment-2327714215>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5P2FUOVN4NWX2X4WXRCTPTZUZMIXAVCNFSM6AAAAABNTBU2OGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRXG4YTIMRRGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-04 02:27 UTC, ncarvajalc requested changes
@PauMurillo28 lo veo bien, chéveres las imágenes, todo muy claro. Dejo esos comentarios de lo que vi así por encima. Súper importante que le comenten a Juan o Luis H que piensen en correos institucionales, dado que delegarle esto a cuentas personales puede que no sea la mejor idea.

Una vez tengas esos cambios, siéntete libre de pedirme otro review y te acepto los cambios.

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/codelab.json
> +  "authors": "Nombre(s) autor(es)",
No olviden ponerse de autores

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/index.html
> +<p>Queremos presentarte una nueva herramienta que puede hacer tu trabajo un poco mas facil. Sabemos que realizar tantos correos diarios puede ser un trabajo un poco largo por lo que te queremos ayuda
Recuerden que esto va a estar disponible para mucha gente. Importante el uso de tildes: más, fácil

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/index.html
> +        <p><strong>BIENVENIDOS!!</strong></p>
Signos de exclamación al inicio ¡¡¡

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/index.html
> +<p>Esta herramienta esta diseñada para 3 tareas: Crear correos y mensajes, actualizar, modificar o recibir retroalimentación y corrección de correos o mensajes. Para que esta herramienta funcione cor
páginas. Ojo con las tildes

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/index.html
> +<li>Contesta cada pregunta de forma clara y específica (estas son necesarias para que kennet pueda hacer su mejor trabajo). </li>
¿Van a usar puntos finales después de cada bullet o no? Deben ser consistentes

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/index.html
> +<li>El chat te proporcionará tres opciones de correo o mensaje, elige la que más te guste y pide correcciones si consideras necesario.. </li>
Hay un doble punto al final

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/index.html
> +<li>Proporciona el correo electrónico o mensaje sobre el cual quieras recibir retroalimentación.. </li>
Aqui hay doble punto final (..)

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/index.html
> +<li>Espera a que el chat corrija tu mensaje. Podrás ver exactamente qué ajustes se hicieron </li>
Falta punto final acá

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/index.html
> +<p><a href="mailto:a.serranoa2@uniandes.edu.co" target="_blank">a.serranoa2@uniandes.edu.co</a></p>
Como sugerencia deberían crear una cuenta de corre institucional, ya sea para IAu o para el equipo de educación. El día que alguno de ustedes se gradúe o que se cambien de frente puede que ya no tenga vigencia el correo. Como mínimo debería estar el correo de todos los del equipo educativo, no de solo una persona.

2024-09-04 02:27 UTC, ncarvajalc commented on codelabs/asistente-correos/index.html
> +<p><strong>FELICITACIONES YA SABES USAR KENNET!!🥳</strong></p>
Signos de admiración iniciales (¡¡¡)

2024-09-06 17:40 UTC, PauMurillo28 commented
Holaa, he hecho los cambios que solicitaste. Subí el codelab de asistente correos con los cambios y además otro para el asistente de actas. Agradecería mucho si pudieras revisarlos. Estoy atenta.

Con respecto al correo, lo comentaré hoy en la reunión con el equipo.

Muchas gracias por tu retroalimentación.

2024-09-06 17:45 UTC, ncarvajalc commented
Listo @PauMurillo28. Por ahora lo voy a aprobar. Le mandé la invitación a @WARRIOR1607 (Andrés Guerrero) para que también pueda colaborar en el repo. En estos momentos no podría hacer la revisión, pero avísame a todos los que estén en el equipo para añadirlos al repositorio y que puedan hacerse retroalimentación entre todos

2024-09-06 17:46 UTC, ncarvajalc approved these changes

2024-09-06 17:46 UTC, merged